version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        # patch and minor updates don't matter for libraries
        # remove this ignore rule if your package has binaries
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
