name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: strum - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - 1.66.1
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
